Repository AY2425S1-CS2103-F11-2/tp, pull requests merged in 2024-10, with the labels that each got.

#46 Add delete contact command
  src/main/java/tutorease/address/logic/commands/DeleteCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteContactCommand.java
  src/main/java/tutorease/address/logic/commands/ListContactCommand.java
  src/main/java/tutorease/address/logic/parser/ContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/DeleteCommandParser.java
  src/main/java/tutorease/address/logic/parser/DeleteContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/TutorEaseParser.java
  src/test/java/tutorease/address/logic/LogicManagerTest.java
  src/test/java/tutorease/address/logic/commands/DeleteCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/ListContactCommandTest.java
  src/test/java/tutorease/address/logic/parser/ContactCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/DeleteContactCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/TutorEaseParserTest.java
Labels: priority.High

#61 Add junit test for DeleteLessonCommand
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
Labels: priority.High

#65 Add junit test for DeleteLessonCommandParser
  src/test/java/tutorease/address/logic/parser/DeleteLessonCommandParserTest.java
Labels: priority.High

#66 Add junit for delete lesson methods in ModelManager
  src/test/java/tutorease/address/model/ModelManagerTest.java
Labels: priority.High

#68 Add junit methods relevant to deleting lessons in UniqueLessonListTest
  src/test/java/tutorease/address/model/lesson/UniqueLessonListTest.java
Labels: priority.High

#74 Add javadocs for delete lesson related methods in LessonSchedule
  src/main/java/tutorease/address/model/LessonSchedule.java
Labels: priority.High

#84 Add List Lesson Command
  src/main/java/tutorease/address/logic/commands/ListLessonCommand.java
  src/main/java/tutorease/address/logic/parser/LessonCommandParser.java
Labels: priority.High

#82 Add student guardian role inside the Person entity
  src/main/java/tutorease/address/logic/commands/AddContactCommand.java
  src/main/java/tutorease/address/logic/commands/EditCommand.java
  src/main/java/tutorease/address/logic/parser/AddContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/CliSyntax.java
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/main/java/tutorease/address/model/person/Person.java
  src/main/java/tutorease/address/model/person/Role.java
  src/main/java/tutorease/address/model/util/SampleDataUtil.java
  src/main/java/tutorease/address/storage/JsonAdaptedPerson.java
  src/main/java/tutorease/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableTutorEaseTest/duplicatePersonTutorEase.json
  src/test/data/JsonSerializableTutorEaseTest/typicalPersonsTutorEase.json
  src/test/java/tutorease/address/logic/LogicManagerTest.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/tutorease/address/model/person/PersonTest.java
  src/test/java/tutorease/address/model/person/RoleTest.java
  src/test/java/tutorease/address/storage/JsonAdaptedPersonTest.java
  src/test/java/tutorease/address/testutil/PersonBuilder.java
  src/test/java/tutorease/address/testutil/PersonUtil.java
  src/test/java/tutorease/address/testutil/TypicalPersons.java
Labels: priority.High

#63 Add junit test for DeleteLessonCommand integration
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandIntegrationTest.java
Labels: priority.High

#71 Add delete all lessons of a person function
  src/main/java/tutorease/address/model/Model.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tutorease/address/model/ModelManagerTest.java
Labels: priority.High

#77 Add delete lessons to UG
  docs/UserGuide.md
Labels: priority.High

#79 Add delete lesson test case to DG
  docs/DeveloperGuide.md
Labels: priority.High

#92 Add lesson model junit test
  src/main/java/tutorease/address/commons/util/DateTimeUtil.java
  src/main/java/tutorease/address/model/lesson/DateTime.java
  src/test/java/tutorease/address/model/lesson/LessonTest.java
  src/test/java/tutorease/address/model/lesson/StudentIdTest.java
  src/test/java/tutorease/address/model/lesson/UniqueLessonListTest.java
Labels: priority.High

#88 Add student class
  src/main/java/tutorease/address/logic/commands/EditCommand.java
  src/main/java/tutorease/address/logic/parser/AddContactCommandParser.java
  src/main/java/tutorease/address/model/person/Person.java
  src/main/java/tutorease/address/model/person/Student.java
  src/main/java/tutorease/address/model/util/SampleDataUtil.java
  src/main/java/tutorease/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableTutorEaseTest/typicalPersonsTutorEase.json
  src/test/java/tutorease/address/logic/LogicManagerTest.java
  src/test/java/tutorease/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/EditCommandTest.java
  src/test/java/tutorease/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/TutorEaseParserTest.java
  src/test/java/tutorease/address/model/TutorEaseTest.java
  src/test/java/tutorease/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/tutorease/address/model/person/StudentTest.java
  src/test/java/tutorease/address/model/person/UniquePersonListTest.java
  src/test/java/tutorease/address/storage/JsonAdaptedLessonTest.java
  src/test/java/tutorease/address/testutil/LessonBuilder.java
  src/test/java/tutorease/address/testutil/StudentBuilder.java
  src/test/java/tutorease/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement

#96 Update JsonAdaptedLesson equals
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/main/java/tutorease/address/model/lesson/DateTime.java
  src/main/java/tutorease/address/model/lesson/EndDateTime.java
  src/main/java/tutorease/address/model/lesson/StartDateTime.java
  src/main/java/tutorease/address/storage/JsonAdaptedLesson.java
  src/test/java/tutorease/address/model/lesson/StartDateTimeTest.java
  src/test/java/tutorease/address/storage/JsonAdaptedLessonTest.java
Labels: priority.High

#101 Update DG to include lesson list command
  docs/UserGuide.md
Labels: priority.High, severity.Low

#99 Update DG to include lesson add command
  docs/UserGuide.md
  src/test/java/tutorease/address/storage/JsonAdaptedLessonTest.java
Labels: priority.High, severity.Low

#75 Add javadocs for delete lesson related methods in UniqueLessonList
  src/main/java/tutorease/address/model/lesson/UniqueLessonList.java
Labels: priority.High

#108 Add junit for deleteStudentLesson
  src/test/java/tutorease/address/model/ModelManagerTest.java
Labels: priority.High

#110 Add delete lessons to command list
  docs/UserGuide.md
Labels: priority.High

#112 Increase StorageManager JUnit test coverage
  docs/DeveloperGuide.md
  src/main/java/tutorease/address/storage/JsonLessonScheduleStorage.java
  src/test/data/JsonLessonScheduleStorageTest/duplicateLessonSchedule.json
  src/test/data/JsonLessonScheduleStorageTest/invalidAndValidLessonSchedule.json
  src/test/data/JsonLessonScheduleStorageTest/invalidLessonSchedule.json
  src/test/data/JsonLessonScheduleStorageTest/notJsonFormatLessonSchedule.json
  src/test/java/tutorease/address/storage/JsonLessonScheduleStorageTest.java
Labels: severity.VeryLow, priority.Low

#114 Update DG to include lesson add command
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow

#116 Change UI title to Tutorease
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.VeryLow

#118 Update markdown Ui image
  docs/images/Ui-Prototype.png
  docs/images/Ui.png
  src/main/java/tutorease/address/storage/JsonAdaptedPerson.java
Labels: priority.High, severity.VeryLow

#103 Implement person subclasses
  src/main/java/tutorease/address/logic/parser/AddContactCommandParser.java
  src/main/java/tutorease/address/model/person/Role.java
  src/main/java/tutorease/address/storage/JsonAdaptedPerson.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/tutorease/address/model/person/RoleTest.java
  src/test/java/tutorease/address/storage/JsonLessonScheduleStorageTest.java
Labels: priority.Medium, type.Enhancement

#119 Update UG to update new contact commands
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#121 Update DG to update contacts commands
  docs/DeveloperGuide.md
Labels: priority.High

#126 Touch up commands and address corner cases
  src/main/java/tutorease/address/logic/commands/ListContactCommand.java
  src/main/java/tutorease/address/logic/commands/ListLessonCommand.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandIntegrationTest.java
  src/test/java/tutorease/address/logic/commands/ListContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/ListLessonCommandTest.java
  src/test/java/tutorease/address/storage/StorageManagerTest.java
  src/test/java/tutorease/address/testutil/TypicalLessons.java
Labels: priority.Medium

#137 Add find lesson command parser
  src/main/java/tutorease/address/logic/parser/FindLessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/LessonCommandParser.java
Labels: priority.High, severity.High

#129 Fix ui resize issue to grow accordingly
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.VeryLow

#131 Fix bug when creating lesson on filtered contacts
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
Labels: priority.High, type.Bug, severity.High

#133 Update add lesson command to add in order
  src/main/java/tutorease/address/model/lesson/DateTime.java
  src/main/java/tutorease/address/model/lesson/Lesson.java
  src/main/java/tutorease/address/model/lesson/StartDateTime.java
  src/main/java/tutorease/address/model/lesson/UniqueLessonList.java
Labels: priority.Medium, type.Enhancement, severity.Medium

#139 Add junit for find lesson command
  src/test/java/tutorease/address/logic/commands/FindLessonCommandTest.java
Labels: priority.High, severity.High

#143 Add junit for FindLessonCommandParser
  src/main/java/tutorease/address/logic/parser/FindLessonCommandParser.java
  src/test/java/tutorease/address/logic/parser/FindLessonCommandParserTest.java
Labels: priority.High, severity.High

#145 Add junit for LessonContainsNamesPredicate
  src/test/java/tutorease/address/model/lesson/LessonContainsNamesPredicateTest.java
Labels: priority.High, severity.High

#149 Remove optional locationId field
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
  src/main/java/tutorease/address/logic/parser/AddLessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/CliSyntax.java
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/main/java/tutorease/address/model/lesson/Lesson.java
  src/main/java/tutorease/address/model/lesson/LocationIndex.java
  src/main/java/tutorease/address/model/person/Person.java
  src/main/java/tutorease/address/storage/JsonAdaptedLesson.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandIntegrationTest.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandIntegrationTest.java
  src/test/java/tutorease/address/logic/commands/ListLessonCommandTest.java
  src/test/java/tutorease/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/TutorEaseParserTest.java
  src/test/java/tutorease/address/model/lesson/LessonTest.java
  src/test/java/tutorease/address/model/lesson/LocationIndexTest.java
  src/test/java/tutorease/address/model/lesson/StudentIdTest.java
  src/test/java/tutorease/address/storage/JsonAdaptedLessonTest.java
  src/test/java/tutorease/address/testutil/LessonBuilder.java
  src/test/java/tutorease/address/testutil/TypicalLessons.java
Labels: priority.High, type.Enhancement, severity.Medium

#151 Fix DG layout issue
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow, type.Bug

#146 Update UG with lesson find
  docs/UserGuide.md
  docs/images/beforeFindLesson.png
  docs/images/findLessonJohnAliceResult.png
  docs/images/findLessonJohnResult.png
  src/test/java/tutorease/address/logic/commands/FindLessonCommandTest.java
Labels: priority.High, severity.High

#152 Update formatting in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.VeryLow

#144 Add more test cases about toString and equals
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
Labels: type.Enhancement, severity.Low

#156 Update user cases in DG to include find contact command
  docs/DeveloperGuide.md
  src/main/java/tutorease/address/logic/commands/FindContactCommand.java
  src/test/java/tutorease/address/logic/commands/FindContactCommandTest.java
Labels: priority.High

#159 Refactor classes to extend comparable interface
  src/main/java/tutorease/address/model/lesson/DateTime.java
  src/main/java/tutorease/address/model/lesson/Lesson.java
Labels: priority.Medium, type.Enhancement, severity.VeryLow

#160 Add more tests in Logic Manager and Delete Lesson Command to increase test coverage
  src/main/java/tutorease/address/logic/commands/DeleteContactCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteLessonCommand.java
  src/test/java/tutorease/address/logic/LogicManagerTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
Labels: priority.Medium

#163 Update Ui class puml and DG
  _markbind/logs/.4a27e4dd4d52b0b210ca13b42ac22c488093fce8-audit.json
  _markbind/logs/markbind-2024-10-22.log
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High, type.Enhancement, severity.VeryLow

#169 Enable assertions
  build.gradle
Labels: priority.High, type.Enhancement

#165 Update lesson card UI
  src/main/java/tutorease/address/model/lesson/Lesson.java
  src/main/java/tutorease/address/ui/LessonCard.java
  src/main/java/tutorease/address/ui/LessonListPanel.java
  src/main/resources/view/LessonListCard.fxml
  src/test/java/tutorease/address/model/lesson/LessonTest.java
Labels: priority.High, type.Enhancement, severity.Medium

#175 Update lesson UG
  docs/UserGuide.md
Labels: priority.High, type.Enhancement, severity.VeryLow

#171 Update UserGuide to include contact find and contact edit
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: priority.High

#167 Update EditCommand class to EditContactCommand class
  src/main/java/tutorease/address/logic/commands/EditContactCommand.java
  src/main/java/tutorease/address/logic/parser/ContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/EditContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/TutorEaseParser.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/commands/EditContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/tutorease/address/logic/parser/ContactCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/EditContactCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/TutorEaseParserTest.java
  src/test/java/tutorease/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/tutorease/address/testutil/PersonUtil.java
Labels: priority.High

#179 Edit logic class diagram and DG
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
Labels: priority.High, severity.Medium

#181 Add logger to FindLessonCommand
  src/main/java/tutorease/address/commons/core/LogsCenter.java
  src/main/java/tutorease/address/logic/commands/FindLessonCommand.java
Labels: priority.Medium, severity.Medium

#183 Update Model UML Diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High

#189 Edit lesson duration constraints
  src/main/java/tutorease/address/model/lesson/EndDateTime.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tutorease/address/model/lesson/EndDateTimeTest.java
Labels: priority.High, severity.High, alpha-bug

#194 Edit filtered add lesson
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
Labels: priority.High, type.Enhancement, severity.High

#202 Fix bug where lessons can be created for guardians
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
  src/main/java/tutorease/address/model/person/Guardian.java
  src/main/java/tutorease/address/model/person/Person.java
  src/main/java/tutorease/address/model/person/Student.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/model/person/GuardianTest.java
Labels: priority.High, type.Bug, severity.High, alpha-bug

#190 Edit datetime errors to make them more specific
  src/main/java/tutorease/address/commons/util/DateTimeUtil.java
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/main/java/tutorease/address/model/lesson/DateTime.java
  src/main/java/tutorease/address/model/lesson/EndDateTime.java
  src/main/java/tutorease/address/model/lesson/StartDateTime.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tutorease/address/model/lesson/EndDateTimeTest.java
  src/test/java/tutorease/address/model/lesson/StartDateTimeTest.java
Labels: priority.High, type.Enhancement, severity.High

#196 Ensure clear command also clear lessons
  src/main/java/tutorease/address/MainApp.java
  src/main/java/tutorease/address/logic/commands/ClearCommand.java
  src/main/java/tutorease/address/model/LessonSchedule.java
  src/main/java/tutorease/address/model/Model.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/main/java/tutorease/address/model/ReadOnlyLessonSchedule.java
  src/main/java/tutorease/address/model/util/SampleDataUtil.java
  src/main/java/tutorease/address/storage/JsonLessonScheduleStorage.java
  src/main/java/tutorease/address/storage/JsonSerializableLessonSchedule.java
  src/main/java/tutorease/address/storage/LessonScheduleStorage.java
  src/main/java/tutorease/address/storage/Storage.java
  src/main/java/tutorease/address/storage/StorageManager.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tutorease/address/model/ModelManagerTest.java
  src/test/java/tutorease/address/storage/JsonLessonScheduleStorageTest.java
  src/test/java/tutorease/address/storage/StorageManagerTest.java
Labels: priority.High, severity.High

#201 Update help command to show the right UG
  docs/images/helpMessage.png
  docs/images/help_message.png
  src/main/java/tutorease/address/ui/HelpWindow.java
Labels: priority.Medium, type.Enhancement

#205 Update commands to not be case sensitive
  src/main/java/tutorease/address/logic/commands/ListLessonCommand.java
  src/main/java/tutorease/address/logic/parser/TutorEaseParser.java
  src/test/java/tutorease/address/logic/parser/TutorEaseParserTest.java
  src/test/java/tutorease/address/testutil/CommandsUtil.java
Labels: priority.High, type.Bug, severity.High, alpha-bug

#213 Deleting students should result in deleting the corresponding lessons
  src/main/java/tutorease/address/logic/commands/DeleteContactCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteLessonCommand.java
  src/main/java/tutorease/address/model/LessonSchedule.java
  src/main/java/tutorease/address/model/Model.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/main/java/tutorease/address/model/lesson/UniqueLessonList.java
  src/main/java/tutorease/address/model/lesson/exceptions/LessonNotInList.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tutorease/address/model/LessonScheduleTest.java
  src/test/java/tutorease/address/model/ModelManagerTest.java
  src/test/java/tutorease/address/model/lesson/UniqueLessonListTest.java
  src/test/java/tutorease/address/storage/JsonLessonScheduleStorageTest.java
Labels: alpha-bug
