Repository AY2425S1-CS2103-F11-2/tp, pull requests merged in 2024-11, with the labels that each got.

#221 [Contacts] Update prefix
  src/main/java/tutorease/address/logic/parser/AddContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/ArgumentTokenizer.java
  src/main/java/tutorease/address/logic/parser/CliSyntax.java
  src/test/java/tutorease/address/logic/commands/CommandTestUtil.java
  src/test/java/tutorease/address/logic/parser/AddContactCommandParserTest.java
Labels: priority.High, type.Bug, severity.Medium, alpha-bug

#212 Add specific error message for each prefix
  src/main/java/tutorease/address/logic/Messages.java
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
  src/main/java/tutorease/address/logic/parser/AddLessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/ArgumentMultimap.java
  src/main/java/tutorease/address/logic/parser/ArgumentTokenizer.java
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/test/java/tutorease/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/tutorease/address/logic/parser/ArgumentTokenizerTest.java
Labels: priority.Medium, type.Enhancement, severity.Medium, alpha-bug

#222 [Contacts] Role should be case-insensitive
  src/main/java/tutorease/address/model/person/Role.java
  src/test/java/tutorease/address/logic/parser/ParserUtilTest.java
  src/test/java/tutorease/address/model/person/RoleTest.java
Labels: priority.Medium, alpha-bug

#220 Disallow duplicate phone and email to exist
  src/main/java/tutorease/address/logic/commands/AddContactCommand.java
  src/main/java/tutorease/address/model/Model.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/main/java/tutorease/address/model/TutorEase.java
  src/main/java/tutorease/address/model/person/Person.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tutorease/address/model/TutorEaseTest.java
  src/test/java/tutorease/address/model/person/PersonTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#223 [Contacts] Error Message not specific
  src/main/java/tutorease/address/logic/parser/AddContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/test/java/tutorease/address/logic/parser/AddContactCommandParserTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#224 Update and standardise error message
  src/main/java/tutorease/address/logic/Messages.java
  src/main/java/tutorease/address/logic/commands/AddContactCommand.java
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteContactCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteLessonCommand.java
  src/main/java/tutorease/address/logic/commands/FindLessonCommand.java
  src/main/java/tutorease/address/logic/commands/ListContactCommand.java
  src/main/java/tutorease/address/logic/commands/ListLessonCommand.java
  src/main/java/tutorease/address/model/lesson/Lesson.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/model/lesson/LessonTest.java
Labels: priority.High, type.Enhancement, severity.Low, alpha-bug

#188 Update lesson delete to delete correctly after find
  src/main/java/tutorease/address/logic/commands/DeleteLessonCommand.java
  src/main/java/tutorease/address/model/LessonSchedule.java
  src/main/java/tutorease/address/model/Model.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/main/java/tutorease/address/model/lesson/UniqueLessonList.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandIntegrationTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
  src/test/java/tutorease/address/model/LessonScheduleTest.java
  src/test/java/tutorease/address/model/lesson/UniqueLessonListTest.java
Labels: priority.High, severity.High, alpha-bug

#226 Edit contact command
  src/main/java/tutorease/address/logic/Messages.java
  src/main/java/tutorease/address/logic/commands/AddContactCommand.java
  src/main/java/tutorease/address/logic/commands/EditContactCommand.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/EditContactCommandTest.java
Labels: priority.High, severity.High, alpha-bug

#230 Make error message for duration more explicit
  src/main/java/tutorease/address/model/lesson/EndDateTime.java
Labels: priority.High, severity.High, alpha-bug

#229 Increase size of UI result display
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Enhancement, alpha-bug

#235 Update UI uml and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/Ui.png
  docs/images/addLessonUg/add_lesson.png
  docs/images/help_message.png
Labels: priority.High, type.Enhancement

#232 Update UserGuide with updated information
  docs/UserGuide.md
  docs/images/contact-add-Guardian.png
  docs/images/contact-add-Student.png
Labels: priority.High, severity.High, alpha-bug

#237 Update lessons UG
  docs/UserGuide.md
  docs/images/beforeFindLesson.png
  docs/images/findLessonJohnAliceResult.png
  docs/images/findLessonJohnResult.png
Labels: priority.High, type.Enhancement, severity.VeryLow, alpha-bug

#240 Add Ug page break
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High, type.Enhancement

#259 Improve code quality
  build.gradle
  src/main/java/tutorease/address/commons/util/NumbersUtil.java
  src/main/java/tutorease/address/logic/commands/AddLessonCommand.java
  src/main/java/tutorease/address/logic/commands/ListLessonCommand.java
  src/main/java/tutorease/address/logic/parser/AddLessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/FindLessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/LessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/ParserUtil.java
  src/main/java/tutorease/address/model/LessonSchedule.java
  src/main/java/tutorease/address/model/Model.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/main/java/tutorease/address/model/ReadOnlyLessonSchedule.java
  src/main/java/tutorease/address/model/ReadOnlyTutorEase.java
  src/main/java/tutorease/address/model/TutorEase.java
  src/main/java/tutorease/address/model/UserPrefs.java
  src/main/java/tutorease/address/model/lesson/DateTime.java
  src/main/java/tutorease/address/model/lesson/EndDateTime.java
  src/main/java/tutorease/address/model/lesson/Fee.java
  src/main/java/tutorease/address/model/lesson/Lesson.java
  src/main/java/tutorease/address/model/lesson/StartDateTime.java
  src/main/java/tutorease/address/model/lesson/StudentId.java
  src/main/java/tutorease/address/model/lesson/UniqueLessonList.java
  src/main/java/tutorease/address/storage/JsonAdaptedLesson.java
  src/main/java/tutorease/address/storage/JsonLessonScheduleStorage.java
  src/main/java/tutorease/address/storage/JsonSerializableLessonSchedule.java
  src/main/java/tutorease/address/storage/LessonScheduleStorage.java
  src/main/java/tutorease/address/storage/StorageManager.java
  src/main/java/tutorease/address/ui/LessonCard.java
  src/main/java/tutorease/address/ui/LessonListPanel.java
  src/main/java/tutorease/address/ui/MainWindow.java
  src/test/java/tutorease/address/logic/commands/AddContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/AddLessonCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/tutorease/address/logic/commands/DeleteLessonCommandTest.java
Labels: priority.High, type.Enhancement, severity.VeryLow

#245 Add the lesson find use case to the DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.High

#243 Refine UG for duration and find for lessons
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement, severity.Medium

#307 [Contacts] Find command example update
  src/main/java/tutorease/address/logic/commands/FindContactCommand.java
Labels: priority.High, severity.Medium

#308 [UG] Update add and edit command details
  docs/UserGuide.md
Labels: priority.High, severity.Low

#309 [Contacts] Add contact command email error message
  src/main/java/tutorease/address/model/person/Email.java
Labels: priority.High, severity.Low

#310 [UG] Update ug for some bugs and updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/images/UiLayout.png
Labels: priority.High, type.Enhancement, severity.VeryLow

#247 [UG]Enhancements aimed for future iterations
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#311 Remove saving data section
  docs/DeveloperGuide.md
Labels: severity.VeryLow

#312 Remove undo redo
  docs/DeveloperGuide.md
Labels: severity.Low

#313 Specify lesson delete in manual testing [DG]
  docs/DeveloperGuide.md
Labels: severity.Low

#316 Fix model uml to remove composition
  docs/diagrams/ModelClassDiagram.puml
Labels: severity.Medium

#315 Add warnings/notes/glossary for year and integer
  docs/UserGuide.md
Labels: severity.Low

#306 Missing user cases and outdated line about system and actor
  docs/DeveloperGuide.md
Labels: priority.Medium

#317 Add logging in commands
  src/main/java/tutorease/address/logic/commands/ClearCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteContactCommand.java
  src/main/java/tutorease/address/logic/commands/DeleteLessonCommand.java
  src/main/java/tutorease/address/logic/commands/EditContactCommand.java
  src/main/java/tutorease/address/logic/commands/FindContactCommand.java
  src/main/java/tutorease/address/logic/commands/ListContactCommand.java
  src/main/java/tutorease/address/logic/commands/ListLessonCommand.java
  src/main/java/tutorease/address/model/ModelManager.java
Labels: priority.Medium

#318 Improve code quality
  src/main/java/tutorease/address/logic/commands/AddContactCommand.java
  src/main/java/tutorease/address/logic/commands/EditContactCommand.java
  src/main/java/tutorease/address/logic/parser/AddContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/ContactCommandParser.java
  src/main/java/tutorease/address/logic/parser/EditContactCommandParser.java
  src/main/java/tutorease/address/model/ModelManager.java
  src/main/java/tutorease/address/model/person/Address.java
  src/main/java/tutorease/address/model/person/Email.java
  src/main/java/tutorease/address/model/person/Guardian.java
  src/main/java/tutorease/address/model/person/Name.java
  src/main/java/tutorease/address/model/person/Person.java
  src/main/java/tutorease/address/model/person/Phone.java
  src/main/java/tutorease/address/model/person/Role.java
  src/main/java/tutorease/address/model/person/Student.java
  src/main/java/tutorease/address/model/person/UniquePersonList.java
Labels: priority.Medium

#319 Improve code quality
  src/main/java/tutorease/address/logic/commands/DeleteLessonCommand.java
  src/main/java/tutorease/address/logic/commands/FindLessonCommand.java
  src/main/java/tutorease/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/tutorease/address/logic/parser/FindLessonCommandParser.java
  src/main/java/tutorease/address/model/Model.java
Labels: priority.Medium

#321 Give acknowledgement
  docs/DeveloperGuide.md
Labels: priority.High, severity.High

#323 List fix s
  src/main/java/tutorease/address/logic/Messages.java
Labels: priority.High

#324 Update Future Enhancements
  docs/UserGuide.md
Labels: priority.Medium

#328 [DG] Include page break
  docs/DeveloperGuide.md
Labels: priority.High
